---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-gitops
rules:

- verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  apiGroups: [""]
  resources:
  - secrets
  - serviceaccounts

- verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  apiGroups:
  - batch
  resources:
  - jobs

- verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  apiGroups:
  - operator.external-secrets.io
  resources:
  - operatorconfigs

- verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  - secretstores
