---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
- ConfigMap_argocd-tls-certs-cm.yml
- ArgoCD_openshift-gitops.yml
- ClusterRole_cluster-gitops.yml
- ClusterRoleBinding_openshift-gitops-cluster-gitops.yml
