---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: patch-operator

helmCharts:
- name: operators-installer
  releaseName: patch-operator-install
  version: 2.3.7
  repo: https://redhat-cop.github.io/helm-charts
  valuesInline:
    approveManualInstallPlanViaHook: false
    operators:
    - channel: alpha
      installPlanApproval: Manual
      name: patch-operator
      source: community-operators
      sourceNamespace: openshift-marketplace
      csv: patch-operator.v0.1.7
    operatorGroups:
    - name: patch-operator
      createNamespace: true
