---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets-operator

helmCharts:
- name: operators-installer
  releaseName: external-secrets-operator-install
  version: 2.3.7
  repo: https://redhat-cop.github.io/helm-charts
  valuesInline:
    approveManualInstallPlanViaHook: false
    operators:
    - channel: stable
      installPlanApproval: Manual
      name: external-secrets-operator
      source: community-operators
      sourceNamespace: openshift-marketplace
      csv: external-secrets-operator.v0.9.3
    operatorGroups:
    - name: external-secrets-operator
      createNamespace: true
